name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: git config
        run: |
          git config --global user.name "KanadeAlt"
          git config --global user.email "enashinonome264@gmail.com"
      
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison flex libssl-dev build-essential \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            gcc-arm-linux-gnueabihf python3 aria2 cpio

      - name: Clone Proton Clang
        run: |
          mkdir -p proton-clang
          git clone --recursive --depth=1 -j4 https://github.com/kdrag0n/proton-clang -b master proton-clang

      # 4. Set environment variables
      - name: Export build vars
        run: |
          export KERNEL_DIR=$PWD
          export CLANG_PATH=$PWD/proton-clang/bin
          echo "PATH=$CLANG_PATH:/usr/bin:$PATH" >> $GITHUB_ENV
          echo "KERNEL_DIR=$KERNEL_DIR" >> $GITHUB_ENV

      - name: Start kernel build
        run: |
          export PATH="$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export CC=clang
          export LD=ld.lld
          export AR=llvm-ar
          export NM=llvm-nm
          export OBJCOPY=llvm-objcopy
          export OBJDUMP=llvm-objdump
          export STRIP=llvm-strip
          export LLVM=1
          export LLVM_IAS=1
          export KBUILD_BUILD_USER=RenzAlt
          export KBUILD_BUILD_HOST=sherry

          mkdir -p out
          make O=out vendor/vince-perf_defconfig
          make -j$(nproc --all) O=out \

      - name: Clone AnyKernel3
        run: |
          git clone https://github.com/KanariaAlt/Anykernel3 AnyKernel
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/

      - name: Zip kernel
        run: |
          cd AnyKernel
          zip -r9 Kernel-Ysl-$(date +%Y%m%d).zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Ysl
          path: AnyKernel/*.zip
